### ISSUE TITLE
Error in training (num_samples = 0

### ISSUE THREAD

**Issue by otori-bird** [ktaebum/AttentionedDeepPaint#17]
Traceback (most recent call last):
  File "train.py", line 77, in <module>
    main(parser.parse_args())
  File "train.py", line 43, in main
    batch_size=args.batch_size,
  File "G:\PYTHON\python3.5.4\lib\site-packages\torch\utils\data\dataloader.py", line 176, in __init__
    sampler = RandomSampler(dataset)
  File "G:\PYTHON\python3.5.4\lib\site-packages\torch\utils\data\sampler.py", line 66, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

torch version - 1.1.0

should i specify some value in train.py?

**Comment by ktaebum** [comment]
yes you must configure some command line argument
you can refer `train.sh`
